# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands: agent.name -equals DESKTOP-N1HP5K6

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test --verbose
  displayName: 'Run backend tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'  # Pode ser outro formato, se necessário
    testResultsFiles: '**/test-results.xml'  # Altere para o local correto, se estiver gerando o arquivo de resultados
    mergeTestResults: true
    testRunTitle: 'Backend Test Results'
