# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands: agent.name -equals DESKTOP-N1HP5K6

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test --verbose
  displayName: 'Run backend tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results/test-results.xml'  # Ajuste o caminho conforme necessário
    testRunTitle: 'Backend Tests'
    mergeTestResults: true  # Para combinar os resultados, se houver vários arquivos
  condition: succeededOrFailed()  # Para garantir que os resultados sejam publicados, mesmo que os testes falhem
  displayName: 'Publish Test Results'
